-- SQLite
SELECT * FROM grupos;

DELETE FROM estudiantes;

--Gurpo 3.1
INSERT INTO estudiantes (nombre, grupoId) VALUES
('MONSERRATH AGUIRRE SANCHEZ', 1),
('KATHLEEN TAMARA MARTINEZ MARTINES', 1),
('YEICOB ADRIAN CHAVES GAITAN', 1),
('ALANA SALAS BERROCAL', 1),
('ABDIEL MIGUEL GOMEZ MORALES', 1),
('CAMILA FERNANDA GONZALEZ ZAMORA', 1),
('KENDRICK GAEL GUZMAN AGUERO', 1),
('DARIANA MARIA HERNANDEZ ARAYA', 1),
('APRIL PAMELA HERNANDEZ VENEGAS', 1),
('SAMIR ADOLFO PEREZ BENARD', 1),
('JEIDEN DARIEL PEREZ GOMEZ', 1),
('RASHANY SAMIRA PEREZ MARIN', 1),
('SANTIAGO RAFAEL QUIROS RIVERA', 1),
('YARED SEGURA CABALCETA', 1),
('KEISHA NATASHA VENEGAS BRENES', 1),
('ANTHONY MATIAS VARGAS HERNANDEZ', 1),
('CALETH ZUMBADO JIMENEZ', 1);

--Grupo 3.2

INSERT INTO estudiantes (nombre, grupoId) VALUES
('JIMMY JOHASH ELIZONDO SEQUEIRA', 2),
('JOSHUA ANDREY ARTIAGA HURTADO', 2),
('DAIRAN YORDANN BADILLA CORELLA', 2),
('KEYDEANNE KAYLE BRUMLEY LA TOUCHE', 2),
('LIAH SAMANTHA CRUZ SOLANO', 2),
('OSVALDO ANTONIO DAVILA MONTIEL', 2),
('APRIL DANISHA ESCOBAR RUIZ', 2),
('SNAYDER MAURICI ESPINOZA MURILLO', 2),
('ALANIS AISHA GUIDO CHINCHILLA', 2),
('ALEJANDRO GABRI HERNANDEZ QUIROS', 2),
('JADIER ALBERTO JIMENEZ CAMPOS', 2),
('OSCAR ENOC MENDEZ PEREZ', 2),
('LISEN AMANDA MORALES RODRIGUEZ', 2),
('PABLO ADRIAN PRENDAS DELGADO', 2),
('BRIANA LUCIA RODRIGUEZ AGUERO', 2),
('AZTRID YALOTZIN RUEDA CALERO', 2),
('ALONDRA RODRIGUEZ RODRIGUEZ', 2);

--Grupo 3.3
INSERT INTO estudiantes (nombre, grupoId) VALUES ('ALINE CLARISA AGUERO SANCHEZ', 3);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('VALENTINA CASTRO FALLAS', 3);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('KEYLA CHARLOTTE CASTRO GALARZA', 3);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('BRAIS KALEB CESPEDES CARMONA', 3);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('DYLAN ANTONIO CORRALES ALVARADO', 3);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('ANGEL DAVID JIMENEZ SIBAJA', 3);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('DANIELA LOPEZ RIOS', 3);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('DANEYSHA MARTINEZ CHACON', 3);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('CARLOS ANDRES NUÑEZ NUÑEZ', 3);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('GLENDA SOFIA RODRIGUEZ AGUERO', 3);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('FABIANA MARISSA RODRIGUEZ FLORES', 3);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('MATEO AZAEL SILVA ZAPATA', 3);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('YARA MONTSERRA TORRES FERNANDEZ', 3);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('NAZRI GERAD ELIZONDO RODRIGUEZ', 3);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('NEITHAN SAMUEL VARGAS SANCHEZ', 3);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('THIAGO TORRENS TENORIO', 3);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('Joselin Mora Campos', 3);

--Grupo 3.4
INSERT INTO estudiantes (nombre, grupoId) VALUES ('JOSE JULIAN AGUILAR QUIROS', 4);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('ALANNA ZAMIRA ALFARO CUBILLO', 4);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('DEILYN SKARLETH ARCE ORTIZ', 4);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('MAYBELIN ISABEL BRICEÑO RUIZ', 4);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('ALESHKA VANESA MUÑOZ ALFARO', 4);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('ARIADNA IBEL HERNANDEZ BERMUDEZ', 4);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('ABBYGAIL ISABELLA HERNANDEZ VEGA', 4);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('EVANS GABRIEL PADILLA FALLAS', 4);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('JEIKEL QUESADA CENTENO', 4);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('DERIAN JOSUE RAMIREZ SOLANO', 4);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('KEREN JAZMIN ROSTRAN MORERA', 4);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('ELMER ISAAC SOLIS ZUÑIGA', 4);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('JOSEPH EMANUEL VELASQUEZ ROBLES', 4);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('GEISON JULIAN VENEGAS VALVERDE', 4);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('MATHIAS ARGUELLO JIMENEZ', 4);

--Grupo 2.3
INSERT INTO estudiantes (nombre, grupoId) VALUES ('JHOAN ISAAC ARCE ORTIZ', 5);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('MARCO DAVID BOLIVAR REYES', 5);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('IAN MARCOS CASTRO MORALES', 5);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('JEYDEN MATTEO CERDAS SANDOVAL', 5);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('THIAGO MATHIAS CHAVARRIA LINARES', 5);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('JEYCOL ALEXANDER ESPINOZA CARVAJAL', 5);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('EMILY YAZMIN ESPINOZA RODRIGUEZ', 5);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('AMBER VICTORIA FERRETO CARRANZA', 5);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('IAN MATIAS FONSECA CHAVES', 5);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('ROYBIN JOSUE GOMEZ PEREZ', 5);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('DEYSHEL CELESTE HERNANDEZ MEMBREÑO', 5);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('THIAGO ITZAE JUAREZ TREJOS', 5);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('EBONNY LEYLANI LEITON ARAGON', 5);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('NASHLY MELISSA OREGON OBANDO', 5);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('ABIGAIL JOHANA CERDAS RUIZ', 5);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('IAN ANDREY RIVERA AVILA', 5);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('IDAIRA STEPHANIE SEGURA TALABERA', 5);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('CHRISTY RAMOS ROBLES', 5);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('JIEDAN MOYA RODRIGUEZ', 5);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('YEIDELYN SOFIA CUBILLO RUIZ', 5);

--Grupo 2.1
INSERT INTO estudiantes (nombre, grupoId) VALUES ('MICHAEL DANIEL ALVARADO DIAZ', 6);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('DERICK GAHEL CASTRO CAYASSO', 6);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('TRACY YAMAI CORTES QUESADA', 6);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('SANTIAGO SAMUEL GUIDO JIMENEZ', 6);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('JOHN ADAM MONGE AVILA', 6);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('EITHAN RAFAEL MORALES JIMENEZ', 6);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('JASPER MATHIAS MORERA JIMENEZ', 6);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('BRITHZY VALERIA OBANDO RAMOS', 6);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('BRADLEY JAVIER FERNANDEZ ARAYA', 6);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('KEIDER RANGEL ROCHA', 6);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('ISAAC SAMIR PORRAS MARIN', 6);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('LIAN GILBERTO SAMUDIO SALGUERA', 6);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('KIARA DALEZKA UREÑA CHACON', 6);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('MEIBELYN VEGA MATARRITA', 6);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('GENESIS ELENA MONTALBAL BLANCO', 6);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('AXEL VALLE QUIROS', 6);

--Grupo T.1
INSERT INTO estudiantes (nombre, grupoId) VALUES ('SHEYLA NATALIA ARIAS AGUERO', 7);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('NASLY YARITH ESPINOZA ARAYA', 7);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('GADIEL AARON LOPEZ CASTILLO', 7);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('DIANA ESTEFANIA LOPEZ RIOS', 7);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('KEYDELL ANDRES OROZCO LEITON', 7);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('ABDIEL SAID OTAROLA ARROYO', 7);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('ARTHUR ISAAC PEREZ HE', 7);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('LUCIANA JIMENA RODRIGUEZ FLORES', 7);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('SAHILY SOTO ARTAVIA', 7);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('SANTIAGO ZAID VENEGAS VALVERDE', 7);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('EMMA JOSSERI VICTOR CASTILLO', 7);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('DARIEL VILLEGAS ARIAS', 7);

--Grupo T.2
INSERT INTO estudiantes (nombre, grupoId) VALUES ('DOMINICK JOSE ARCE ORTIZ', 8);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('LIAM JOSUE BRENES CANO', 8);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('LIAM MARCK CASTRO MORALES', 8);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('VICTOR ALEJANDRO ESPINALES MAYORGA', 8);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('ALONDRA YESNARI ESTRADA BALLADARES', 8);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('ANTONY GAEL LINARES CUBILLO', 8);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('DERECK MATIAS MARTINEZ AGUILAR', 8);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('CLARISSA MONTES FERNANDEZ', 8);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('ISABELLA ALANNA MURILLO MENDOZA', 8);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('ELIAS JOSUE PRENDAS DELGADO', 8);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('LIA NASHELE TORRES ROSALES', 8);

--Grupo T.3
INSERT INTO estudiantes (nombre, grupoId) VALUES ('MAGDIEL YAEL BEJARANO MOLINA', 9);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('BRIANNA ABIGAIL CHAVES TORRES', 9);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('JAYLON SAMIR DIAZ SALGUERA', 9);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('DEISHANY ARICHELL GATICA TORREZ', 9);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('NICOLAS GODINEZ RIVERA', 9);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('EITHAN DAVID LEAL GOMEZ', 9);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('LUIS EMIR LOBO ROJAS', 9);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('LEAH MOYA ALEMAN', 9);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('KEYLANI NAIARA RODRIGUEZ CASTILLO', 9);
INSERT INTO estudiantes (nombre, grupoId) VALUES ('THIAGO JOSE RODRIGUEZ MOLINA', 9);